# Kong Data Plane Configuration (Community Edition)
ingressController:
  enabled: false

image:
  repository: kong
  tag: "3.10"

secretVolumes:
  - kong-cluster-cert

env:
  role: data_plane
  database: "off"

  # Control plane connection
  cluster_control_plane: kong-cp-kong-cluster.kong.svc.cluster.local:8005
  cluster_telemetry_endpoint: kong-cp-kong-clustertelemetry.kong.svc.cluster.local:8006

  # Authentication certificates
  lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

# Community Edition - no enterprise features
enterprise:
  enabled: false

# Proxy Configuration with External ELB
proxy:
  enabled: true
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

# Disable admin functions on data plane
admin:
  enabled: false

manager:
  enabled: false
